name: Export, unpack and commit the solution to git
run-name: Getting ${{ github.event.inputs.solution_name }} solution from environment ${{ github.event.inputs.environment_url }} environment and committing
on:
  workflow_dispatch:
    inputs:
      artifact_id:
        description: "The Dataverse record ID of the Artifact created by the pipelines."
        required: true
        default: yourartifactid
      solution_name:
        description: "Name of the Solution in Dataverse environment"
        required: true
        default: yoursolutionname
      environment_url:
        description: Https endpoint of your pipeline host Dataverse environment"
        required: true
        default: "https://[your-env].crm.dynamics.com"
      source_branch:
        description: "Branch for the solution commit"
        required: true
        default: main
      commit_message:
        description: "Message to provide for the commit"
        required: true
permissions:
  contents: write
jobs:
  export-unpack-commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Export the managed solution from the artifact created by pipelines
      - name: export-managed-solution-from-artifact
        env:
            CLIENT_ID: ${{secrets.CLIENT_ID}}   
            TENANT_ID: ${{secrets.TENANT_ID}}   
            PowerPlatformSPN: ${{secrets.PowerPlatformSPN}}
        shell: pwsh
        run: |
            Write-Host "Downloading solution"
            $aadHost = "login.microsoftonline.com"
            $clientId = "$env:CLIENT_ID"
            $clientSecret = "$env:PowerPlatformSPN"
            $tenantId = "$env:TENANT_ID"
            
            $url = "${{ github.event.inputs.environment_url }}"
            $options = [System.StringSplitOptions]::RemoveEmptyEntries
            $dataverseHost = $url.Split("://", $options)[1].Split("/")[0]
            
            $body = @{client_id = $clientId; client_secret = $clientSecret; grant_type = "client_credentials"; scope = "https://$dataverseHost/.default"; }
            Write-Host "body=$body"
            $OAuthReq = Invoke-RestMethod -Method Post -Uri "https://$aadHost/$tenantId/oauth2/v2.0/token" -Body $body
            $spnToken = $OAuthReq.access_token
            $headers = New-Object "System.Collections.Generic.Dictionary[[String],[String]]"
            $headers.Add("Authorization", "Bearer $spnToken")
            $headers.Add("Content-Type", "application/json")
            $odataQueryForFileName = "deploymentartifacts(${{ github.event.inputs.artifact_id }})?`$select=name"
            $requestUrl = "https://$dataverseHost/api/data/v9.2/$odataQueryForFileName"    
            Write-Host "odataQueryForFileName=$requestUrl"
            $reponse = Invoke-RestMethod $requestUrl -Method 'GET' -Headers $headers
            
            $solutionName = $reponse.name
            
            $odataQueryForFileContents = "deploymentartifacts(${{ github.event.inputs.artifact_id }})/artifactfile/$value"
            $requestUrl = "https://$dataverseHost/api/data/v9.2/$odataQueryForFileContents"
            $response = Invoke-RestMethod $requestUrl -Method 'GET' -Headers $headers
            Write-Host "response=$response"
            Write-Host "zipfile="${{ github.event.repository.name }}/${{ github.event.inputs.solution_name }}_managed.zip"
            $response.value | Out-File -FilePath "${{ github.event.repository.name }}/${{ github.event.inputs.solution_name }}_managed.zip"
        
      # Export the managed solution
          #- name: export-managed-solution
      #  uses: microsoft/powerplatform-actions/export-solution@v0
      #  with:
      #      environment-url: ${{ github.event.inputs.environment_url}}
      #      app-id: ${{secrets.CLIENT_ID}}
      #      client-secret: ${{ secrets.PowerPlatformSPN }}
      #      tenant-id: ${{secrets.TENANT_ID}}
      #      solution-name: ${{ github.event.inputs.solution_name }}
      #      solution-output-file: ${{ github.event.repository.name }}/${{ github.event.inputs.solution_name }}_managed.zip
      #      overwrite: true
      #      managed: true

      # Unpack the solution
      - name: unpack-managed-solution
        uses: microsoft/powerplatform-actions/unpack-solution@v0
        with:
          solution-file: ${{ github.event.repository.name }}/${{ github.event.inputs.solution_name }}_managed.zip
          solution-folder: ${{ github.event.repository.name }}/
          solution-type: 'Managed'
          process-canvas-apps: true
          overwrite-files: true

      # Commit changes to the existing or new branch
      - name: commit changes
        shell: pwsh
        run: |
          rm -rf ${{ github.event.repository.name }}/${{ github.event.inputs.solution_name }}_managed.zip
          git config user.name "GitHub Actions Bot"
          git config user.email "<>" 
          git pull 
          git add --all
          git commit -am "${{ github.event.inputs.commit_message }}" --allow-empty

      # Push the committed changes to the source branch
      - name: push to ${{ github.event.inputs.source_branch }}
        run: |
          git push origin ${{ github.event.inputs.source_branch }}