name: Export, unpack and commit the solution to git
run-name: Getting ${{ github.event.inputs.solution_name }} solution from environment ${{ github.event.inputs.environment_url }} environment and committing
on:
  workflow_dispatch:
    inputs:
      solution_name:
        description: "Name of the Solution in Dataverse environment"
        required: true
        default: yoursolutionname
      environment_url:
        description: Https endpoint of your pipeline host Dataverse environment"
        required: true
        default: "https://[your-env].crm.dynamics.com"
      source_branch:
        description: "Branch for the solution commit"
        required: true
        default: main
      commit_message:
        description: "Message to provide for the commit"
        required: true
permissions:
  contents: write
jobs:
  export-unpack-commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Export the unmanaged solution
      - name: export-unmanaged-solution
        uses: microsoft/powerplatform-actions/export-solution@v0
        with:
            environment-url: ${{ github.event.inputs.environment_url}}
            app-id: ${{secrets.CLIENT_ID}}
            client-secret: ${{ secrets.POWERPLATFORMSPN }}
            tenant-id: ${{secrets.TENANT_ID}}
            solution-name: ${{ github.event.inputs.solution_name }}
            solution-output-file: ${{ github.event.repository.name }}/${{ github.event.inputs.solution_name }}.zip
            overwrite: true
            run-asynchronously: true
      
      # Export the managed solution
      - name: export-managed-solution
        uses: microsoft/powerplatform-actions/export-solution@v0
        with:
            environment-url: ${{ github.event.inputs.environment_url}}
            app-id: ${{secrets.CLIENT_ID}}
            client-secret: ${{ secrets.PowerPlatformSPN }}
            tenant-id: ${{secrets.TENANT_ID}}
            solution-name: ${{ github.event.inputs.solution_name }}
            solution-output-file: ${{ github.event.repository.name }}/${{ github.event.inputs.solution_name }}_managed.zip
            overwrite: true
            managed: true

      # Unpack the unmanaged solution
      - name: unpack-solution action
        uses: microsoft/powerplatform-actions/unpack-solution@v0
        with:
          solution-file: ${{ github.event.repository.name }}/${{ github.event.inputs.solution_name }}.zip
          solution-folder: ${{ github.event.repository.name }}/${{ github.event.inputs.solution_name }}
          solution-type: 'Both'
          process-canvas-apps: true
          overwrite-files: true

      # Commit changes to the existing or new branch
      - name: commit changes
        shell: pwsh
        run: |
          rm -rf ${{ github.event.repository.name }}/${{ github.event.inputs.solution_name }}.zip
          rm -rf ${{ github.event.repository.name }}/${{ github.event.inputs.solution_name }}_managed.zip
          git config user.name "GitHub Actions Bot"
          git config user.email "<>" 
          git pull 
          git add --all
          git commit -am "${{ github.event.inputs.commit_message }}" --allow-empty

      # Push the committed changes to the source branch
      - name: push to ${{ github.event.inputs.source_branch }}
        run: |
          git push origin ${{ github.event.inputs.source_branch }}